# 
# more information can be found here http://sonata-project.org/bundles/news
#
nz_portfolio:
    permalink_generator: nz.portfolio.permalink.slug 
    
    class:
        work:           Application\Nz\PortfolioBundle\Entity\Work    
        tag:            Application\Sonata\ClassificationBundle\Entity\Tag
        collection:     Application\Sonata\ClassificationBundle\Entity\Collection
        media:          Application\Sonata\MediaBundle\Entity\Media
        gallery:        Application\Sonata\MediaBundle\Entity\Gallery
        
# Enable Doctrine to map the provided entities
doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                        NzPortfolioBundle: ~
                #ApplicationSonataNewsBundle: ~
                    #AppBundle:
                    #    type: xml
                    #    dir: SomeResources/config/doctrine
