# 
# more information can be found here http://sonata-project.org/bundles/news
#
sonata_news:
    title:        %sonata_news.blog_title%
    link:         %sonata_news.blog_link%
    description:  %sonata_news.blog_description%
    salt:         %sonata_news.salt%

    permalink_generator: sonata.news.permalink.collection 
    #permalink_generator: sonata.news.permalink.date # /2011/12/31/new-year

    # comment options
    comment:
        notification:
            emails:   %sonata_news.comment.emails%
            from:     %sonata_news.comment.email_from%
            template: 'SonataNewsBundle:Mail:comment_notification.txt.twig'
    
    class:
        tag:        Application\Sonata\ClassificationBundle\Entity\Tag
        collection:   Application\Sonata\ClassificationBundle\Entity\Collection
        post:       Application\Sonata\NewsBundle\Entity\Post
        comment:    Application\Sonata\NewsBundle\Entity\Comment
        media:      Application\Sonata\MediaBundle\Entity\Media
        user:       Application\Sonata\UserBundle\Entity\User

    admin:
        post:
            class:       Application\Sonata\NewsBundle\Admin\PostAdmin
            #class:       Sonata\NewsBundle\Admin\PostAdmin
            controller:  SonataAdminBundle:CRUD
            translation: SonataNewsBundle
        comment:
            class:       Sonata\NewsBundle\Admin\CommentAdmin
            controller:  SonataAdminBundle:CRUD
            translation: SonataNewsBundle
        
    
# Enable Doctrine to map the provided entities
doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    ApplicationSonataNewsBundle: ~
                    SonataNewsBundle: ~